// Ciudades (municipios) y departamentos de Paraguay como predeterminado de la
// librería: 263 filas heredadas con su departamento. El autocompletado
// resuelve el departamento solo con la ciudad (es dependiente de ella).
//
// El catálogo es bilingüe: cada fila trae `{ ciudad, departamento }` (español)
// y `{ city, department }` (inglés, el contrato de `CityAutocomplete` y del
// `buscar` propio de cada app). Las dos parejas apuntan al mismo dato; la
// fuente se mantiene en español y la exportada deriva las claves en inglés.
//
// Se actualiza acá y llega a todas las apps con el release de la librería.
// Procedencia heredada: catálogo de municipios compartido con el backend de MobOS.
// Sin enlace oficial verificado en este repositorio: no afirma vigencia oficial.
// Los IDs internos explícitos no son códigos gubernamentales; no se recalculan
// al renombrar o reordenar filas y nunca se deben reutilizar.

const MUNICIPIOS = [
  { id: "oc:locality:py:001", ciudad: "Bahía Negra", departamento: "Alto Paraguay" },
  { id: "oc:locality:py:002", ciudad: "Capitán Carmelo Peralta", departamento: "Alto Paraguay" },
  { id: "oc:locality:py:003", ciudad: "Fuerte Olimpo", departamento: "Alto Paraguay" },
  { id: "oc:locality:py:004", ciudad: "Puerto Casado", departamento: "Alto Paraguay" },
  { id: "oc:locality:py:005", ciudad: "Ciudad del Este", departamento: "Alto Paraná" },
  { id: "oc:locality:py:006", ciudad: "Doctor Juan León Mallorquín", departamento: "Alto Paraná" },
  { id: "oc:locality:py:007", ciudad: "Doctor Raúl Peña", departamento: "Alto Paraná" },
  { id: "oc:locality:py:008", ciudad: "Domingo Martínez de Irala", departamento: "Alto Paraná" },
  { id: "oc:locality:py:009", ciudad: "Hernandarias", departamento: "Alto Paraná" },
  { id: "oc:locality:py:010", ciudad: "Iruña", departamento: "Alto Paraná" },
  { id: "oc:locality:py:011", ciudad: "Itakyry", departamento: "Alto Paraná" },
  { id: "oc:locality:py:012", ciudad: "Juan Emiliano O''Leary", departamento: "Alto Paraná" },
  { id: "oc:locality:py:013", ciudad: "Los Cedrales", departamento: "Alto Paraná" },
  { id: "oc:locality:py:014", ciudad: "Mbaracayú", departamento: "Alto Paraná" },
  { id: "oc:locality:py:015", ciudad: "Minga Guazú", departamento: "Alto Paraná" },
  { id: "oc:locality:py:016", ciudad: "Minga Porá", departamento: "Alto Paraná" },
  { id: "oc:locality:py:017", ciudad: "Naranjal", departamento: "Alto Paraná" },
  { id: "oc:locality:py:018", ciudad: "Ñacunday", departamento: "Alto Paraná" },
  { id: "oc:locality:py:019", ciudad: "Presidente Franco", departamento: "Alto Paraná" },
  { id: "oc:locality:py:020", ciudad: "San Alberto", departamento: "Alto Paraná" },
  { id: "oc:locality:py:021", ciudad: "San Cristóbal", departamento: "Alto Paraná" },
  { id: "oc:locality:py:022", ciudad: "Santa Fe del Paraná", departamento: "Alto Paraná" },
  { id: "oc:locality:py:023", ciudad: "Santa Rita", departamento: "Alto Paraná" },
  { id: "oc:locality:py:024", ciudad: "Santa Rosa del Monday", departamento: "Alto Paraná" },
  { id: "oc:locality:py:025", ciudad: "Tavapy", departamento: "Alto Paraná" },
  { id: "oc:locality:py:026", ciudad: "Yguazú", departamento: "Alto Paraná" },
  { id: "oc:locality:py:027", ciudad: "Bella Vista Norte", departamento: "Amambay" },
  { id: "oc:locality:py:028", ciudad: "Capitán Bado", departamento: "Amambay" },
  { id: "oc:locality:py:029", ciudad: "Cerro Corá", departamento: "Amambay" },
  { id: "oc:locality:py:030", ciudad: "Karapaí", departamento: "Amambay" },
  { id: "oc:locality:py:031", ciudad: "Pedro Juan Caballero", departamento: "Amambay" },
  { id: "oc:locality:py:032", ciudad: "Zanja Pytá", departamento: "Amambay" },
  { id: "oc:locality:py:033", ciudad: "Asunción", departamento: "Asunción" },
  { id: "oc:locality:py:034", ciudad: "Boquerón", departamento: "Boquerón" },
  { id: "oc:locality:py:035", ciudad: "Filadelfia", departamento: "Boquerón" },
  { id: "oc:locality:py:036", ciudad: "Loma Plata", departamento: "Boquerón" },
  { id: "oc:locality:py:037", ciudad: "Mariscal José Félix Estigarribia", departamento: "Boquerón" },
  { id: "oc:locality:py:038", ciudad: "Caaguazú", departamento: "Caaguazú" },
  { id: "oc:locality:py:039", ciudad: "Carayaó", departamento: "Caaguazú" },
  { id: "oc:locality:py:040", ciudad: "Coronel Oviedo", departamento: "Caaguazú" },
  { id: "oc:locality:py:041", ciudad: "Doctor Cecilio Báez", departamento: "Caaguazú" },
  { id: "oc:locality:py:042", ciudad: "Doctor Juan Eulogio Estigarribia", departamento: "Caaguazú" },
  { id: "oc:locality:py:043", ciudad: "Doctor Juan Manuel Frutos", departamento: "Caaguazú" },
  { id: "oc:locality:py:044", ciudad: "José Domingo Ocampos", departamento: "Caaguazú" },
  { id: "oc:locality:py:045", ciudad: "La Pastora", departamento: "Caaguazú" },
  { id: "oc:locality:py:046", ciudad: "Mariscal Francisco Solano López", departamento: "Caaguazú" },
  { id: "oc:locality:py:047", ciudad: "Nueva Londres", departamento: "Caaguazú" },
  { id: "oc:locality:py:048", ciudad: "Nueva Toledo", departamento: "Caaguazú" },
  { id: "oc:locality:py:049", ciudad: "Raúl Arsenio Oviedo", departamento: "Caaguazú" },
  { id: "oc:locality:py:050", ciudad: "Regimiento de Infantería Tres Corrales", departamento: "Caaguazú" },
  { id: "oc:locality:py:051", ciudad: "Repatriación", departamento: "Caaguazú" },
  { id: "oc:locality:py:052", ciudad: "San Joaquín", departamento: "Caaguazú" },
  { id: "oc:locality:py:053", ciudad: "San José de los Arroyos", departamento: "Caaguazú" },
  { id: "oc:locality:py:054", ciudad: "Santa Rosa del Mbutuy", departamento: "Caaguazú" },
  { id: "oc:locality:py:055", ciudad: "Simón Bolívar", departamento: "Caaguazú" },
  { id: "oc:locality:py:056", ciudad: "Tembiaporá", departamento: "Caaguazú" },
  { id: "oc:locality:py:057", ciudad: "Tres de Febrero", departamento: "Caaguazú" },
  { id: "oc:locality:py:058", ciudad: "Vaquería", departamento: "Caaguazú" },
  { id: "oc:locality:py:059", ciudad: "Yhú", departamento: "Caaguazú" },
  { id: "oc:locality:py:060", ciudad: "Abaí", departamento: "Caazapá" },
  { id: "oc:locality:py:061", ciudad: "Buena Vista", departamento: "Caazapá" },
  { id: "oc:locality:py:062", ciudad: "Caazapá", departamento: "Caazapá" },
  { id: "oc:locality:py:063", ciudad: "Doctor Moisés Santiago Bertoni", departamento: "Caazapá" },
  { id: "oc:locality:py:064", ciudad: "Fulgencio Yegros", departamento: "Caazapá" },
  { id: "oc:locality:py:065", ciudad: "General Higinio Morínigo", departamento: "Caazapá" },
  { id: "oc:locality:py:066", ciudad: "Maciel", departamento: "Caazapá" },
  { id: "oc:locality:py:067", ciudad: "San Juan Nepomuceno", departamento: "Caazapá" },
  { id: "oc:locality:py:068", ciudad: "Tavaí", departamento: "Caazapá" },
  { id: "oc:locality:py:069", ciudad: "Tres de Mayo", departamento: "Caazapá" },
  { id: "oc:locality:py:070", ciudad: "Yuty", departamento: "Caazapá" },
  { id: "oc:locality:py:071", ciudad: "Corpus Christi", departamento: "Canindeyú" },
  { id: "oc:locality:py:072", ciudad: "Curuguaty", departamento: "Canindeyú" },
  { id: "oc:locality:py:073", ciudad: "General Francisco Caballero Álvarez", departamento: "Canindeyú" },
  { id: "oc:locality:py:074", ciudad: "Itanará", departamento: "Canindeyú" },
  { id: "oc:locality:py:075", ciudad: "Katueté", departamento: "Canindeyú" },
  { id: "oc:locality:py:076", ciudad: "La Paloma del Espíritu Santo", departamento: "Canindeyú" },
  { id: "oc:locality:py:077", ciudad: "Laurel", departamento: "Canindeyú" },
  { id: "oc:locality:py:078", ciudad: "Maracaná", departamento: "Canindeyú" },
  { id: "oc:locality:py:079", ciudad: "Nueva Esperanza", departamento: "Canindeyú" },
  { id: "oc:locality:py:080", ciudad: "Puerto Adela", departamento: "Canindeyú" },
  { id: "oc:locality:py:081", ciudad: "Saltos del Guairá", departamento: "Canindeyú" },
  { id: "oc:locality:py:082", ciudad: "Villa Ygatimí", departamento: "Canindeyú" },
  { id: "oc:locality:py:083", ciudad: "Yasy Cañy", departamento: "Canindeyú" },
  { id: "oc:locality:py:084", ciudad: "Yby Pytá", departamento: "Canindeyú" },
  { id: "oc:locality:py:085", ciudad: "Ybyrarobaná", departamento: "Canindeyú" },
  { id: "oc:locality:py:086", ciudad: "Ypejhú", departamento: "Canindeyú" },
  { id: "oc:locality:py:087", ciudad: "Areguá", departamento: "Central" },
  { id: "oc:locality:py:088", ciudad: "Capiatá", departamento: "Central" },
  { id: "oc:locality:py:089", ciudad: "Fernando de la Mora", departamento: "Central" },
  { id: "oc:locality:py:090", ciudad: "Guarambaré", departamento: "Central" },
  { id: "oc:locality:py:091", ciudad: "Itá", departamento: "Central" },
  { id: "oc:locality:py:092", ciudad: "Itauguá", departamento: "Central" },
  { id: "oc:locality:py:093", ciudad: "Julián Augusto Saldívar", departamento: "Central" },
  { id: "oc:locality:py:094", ciudad: "Lambaré", departamento: "Central" },
  { id: "oc:locality:py:095", ciudad: "Limpio", departamento: "Central" },
  { id: "oc:locality:py:096", ciudad: "Luque", departamento: "Central" },
  { id: "oc:locality:py:097", ciudad: "Mariano Roque Alonso", departamento: "Central" },
  { id: "oc:locality:py:098", ciudad: "Nueva Italia", departamento: "Central" },
  { id: "oc:locality:py:099", ciudad: "Ñemby", departamento: "Central" },
  { id: "oc:locality:py:100", ciudad: "San Antonio", departamento: "Central" },
  { id: "oc:locality:py:101", ciudad: "San Lorenzo", departamento: "Central" },
  { id: "oc:locality:py:102", ciudad: "Villa Elisa", departamento: "Central" },
  { id: "oc:locality:py:103", ciudad: "Villeta", departamento: "Central" },
  { id: "oc:locality:py:104", ciudad: "Ypacaraí", departamento: "Central" },
  { id: "oc:locality:py:105", ciudad: "Ypané", departamento: "Central" },
  { id: "oc:locality:py:106", ciudad: "Arroyito", departamento: "Concepción" },
  { id: "oc:locality:py:107", ciudad: "Azotey", departamento: "Concepción" },
  { id: "oc:locality:py:108", ciudad: "Belén", departamento: "Concepción" },
  { id: "oc:locality:py:109", ciudad: "Concepción", departamento: "Concepción" },
  { id: "oc:locality:py:110", ciudad: "Horqueta", departamento: "Concepción" },
  { id: "oc:locality:py:111", ciudad: "Itacuá", departamento: "Concepción" },
  { id: "oc:locality:py:112", ciudad: "Loreto", departamento: "Concepción" },
  { id: "oc:locality:py:113", ciudad: "Paso Barreto", departamento: "Concepción" },
  { id: "oc:locality:py:114", ciudad: "Paso Horqueta", departamento: "Concepción" },
  { id: "oc:locality:py:115", ciudad: "San Alfredo", departamento: "Concepción" },
  { id: "oc:locality:py:116", ciudad: "San Carlos del Apa", departamento: "Concepción" },
  { id: "oc:locality:py:117", ciudad: "San Lázaro", departamento: "Concepción" },
  { id: "oc:locality:py:118", ciudad: "Sargento José Félix López", departamento: "Concepción" },
  { id: "oc:locality:py:119", ciudad: "Yby Yaú", departamento: "Concepción" },
  { id: "oc:locality:py:120", ciudad: "Altos", departamento: "Cordillera" },
  { id: "oc:locality:py:121", ciudad: "Arroyos y Esteros", departamento: "Cordillera" },
  { id: "oc:locality:py:122", ciudad: "Atyrá", departamento: "Cordillera" },
  { id: "oc:locality:py:123", ciudad: "Caacupé", departamento: "Cordillera" },
  { id: "oc:locality:py:124", ciudad: "Caraguatay", departamento: "Cordillera" },
  { id: "oc:locality:py:125", ciudad: "Emboscada", departamento: "Cordillera" },
  { id: "oc:locality:py:126", ciudad: "Eusebio Ayala", departamento: "Cordillera" },
  { id: "oc:locality:py:127", ciudad: "Isla Pucú", departamento: "Cordillera" },
  { id: "oc:locality:py:128", ciudad: "Itacurubí de la Cordillera", departamento: "Cordillera" },
  { id: "oc:locality:py:129", ciudad: "Juan de Mena", departamento: "Cordillera" },
  { id: "oc:locality:py:130", ciudad: "Loma Grande", departamento: "Cordillera" },
  { id: "oc:locality:py:131", ciudad: "Mbocayaty del Yhaguy", departamento: "Cordillera" },
  { id: "oc:locality:py:132", ciudad: "Nueva Colombia", departamento: "Cordillera" },
  { id: "oc:locality:py:133", ciudad: "Piribebuy", departamento: "Cordillera" },
  { id: "oc:locality:py:134", ciudad: "Primero de Marzo", departamento: "Cordillera" },
  { id: "oc:locality:py:135", ciudad: "San Bernardino", departamento: "Cordillera" },
  { id: "oc:locality:py:136", ciudad: "San José Obrero", departamento: "Cordillera" },
  { id: "oc:locality:py:137", ciudad: "Santa Elena", departamento: "Cordillera" },
  { id: "oc:locality:py:138", ciudad: "Tobatí", departamento: "Cordillera" },
  { id: "oc:locality:py:139", ciudad: "Valenzuela", departamento: "Cordillera" },
  { id: "oc:locality:py:140", ciudad: "Borja", departamento: "Guairá" },
  { id: "oc:locality:py:141", ciudad: "Capitán Mauricio José Troche", departamento: "Guairá" },
  { id: "oc:locality:py:142", ciudad: "Coronel Martínez", departamento: "Guairá" },
  { id: "oc:locality:py:143", ciudad: "Doctor Botrell", departamento: "Guairá" },
  { id: "oc:locality:py:144", ciudad: "Félix Pérez Cardozo", departamento: "Guairá" },
  { id: "oc:locality:py:145", ciudad: "General Eugenio Alejandrino Garay", departamento: "Guairá" },
  { id: "oc:locality:py:146", ciudad: "Independencia", departamento: "Guairá" },
  { id: "oc:locality:py:147", ciudad: "Itapé", departamento: "Guairá" },
  { id: "oc:locality:py:148", ciudad: "Iturbe", departamento: "Guairá" },
  { id: "oc:locality:py:149", ciudad: "José A. Fassardi", departamento: "Guairá" },
  { id: "oc:locality:py:150", ciudad: "Mbocayaty del Guairá", departamento: "Guairá" },
  { id: "oc:locality:py:151", ciudad: "Natalicio Talavera", departamento: "Guairá" },
  { id: "oc:locality:py:152", ciudad: "Ñumí", departamento: "Guairá" },
  { id: "oc:locality:py:153", ciudad: "Paso Yobái", departamento: "Guairá" },
  { id: "oc:locality:py:154", ciudad: "San Salvador", departamento: "Guairá" },
  { id: "oc:locality:py:155", ciudad: "Tebicuary", departamento: "Guairá" },
  { id: "oc:locality:py:156", ciudad: "Villarrica", departamento: "Guairá" },
  { id: "oc:locality:py:157", ciudad: "Yataity del Guairá", departamento: "Guairá" },
  { id: "oc:locality:py:158", ciudad: "Alto Verá", departamento: "Itapúa" },
  { id: "oc:locality:py:159", ciudad: "Bella Vista", departamento: "Itapúa" },
  { id: "oc:locality:py:160", ciudad: "Cambyretá", departamento: "Itapúa" },
  { id: "oc:locality:py:161", ciudad: "Capitán Meza", departamento: "Itapúa" },
  { id: "oc:locality:py:162", ciudad: "Capitán Miranda", departamento: "Itapúa" },
  { id: "oc:locality:py:163", ciudad: "Carlos Antonio López", departamento: "Itapúa" },
  { id: "oc:locality:py:164", ciudad: "Carmen del Paraná", departamento: "Itapúa" },
  { id: "oc:locality:py:165", ciudad: "Coronel José Félix Bogado", departamento: "Itapúa" },
  { id: "oc:locality:py:166", ciudad: "Edelira", departamento: "Itapúa" },
  { id: "oc:locality:py:167", ciudad: "Encarnación", departamento: "Itapúa" },
  { id: "oc:locality:py:168", ciudad: "Fram", departamento: "Itapúa" },
  { id: "oc:locality:py:169", ciudad: "General Artigas", departamento: "Itapúa" },
  { id: "oc:locality:py:170", ciudad: "General Delgado", departamento: "Itapúa" },
  { id: "oc:locality:py:171", ciudad: "Hohenau", departamento: "Itapúa" },
  { id: "oc:locality:py:172", ciudad: "Itapúa Poty", departamento: "Itapúa" },
  { id: "oc:locality:py:173", ciudad: "Jesús de Tavarangüé", departamento: "Itapúa" },
  { id: "oc:locality:py:174", ciudad: "José Leandro Oviedo", departamento: "Itapúa" },
  { id: "oc:locality:py:175", ciudad: "La Paz", departamento: "Itapúa" },
  { id: "oc:locality:py:176", ciudad: "Mayor Julio Dionisio Otaño", departamento: "Itapúa" },
  { id: "oc:locality:py:177", ciudad: "Natalio", departamento: "Itapúa" },
  { id: "oc:locality:py:178", ciudad: "Nueva Alborada", departamento: "Itapúa" },
  { id: "oc:locality:py:179", ciudad: "Obligado", departamento: "Itapúa" },
  { id: "oc:locality:py:180", ciudad: "Pirapó", departamento: "Itapúa" },
  { id: "oc:locality:py:181", ciudad: "San Cosme y Damián", departamento: "Itapúa" },
  { id: "oc:locality:py:182", ciudad: "San Juan del Paraná", departamento: "Itapúa" },
  { id: "oc:locality:py:183", ciudad: "San Pedro del Paraná", departamento: "Itapúa" },
  { id: "oc:locality:py:184", ciudad: "San Rafael del Paraná", departamento: "Itapúa" },
  { id: "oc:locality:py:185", ciudad: "Tomás Romero Pereira", departamento: "Itapúa" },
  { id: "oc:locality:py:186", ciudad: "Trinidad", departamento: "Itapúa" },
  { id: "oc:locality:py:187", ciudad: "Yatytay", departamento: "Itapúa" },
  { id: "oc:locality:py:188", ciudad: "Ayolas", departamento: "Misiones" },
  { id: "oc:locality:py:189", ciudad: "San Ignacio Guazú", departamento: "Misiones" },
  { id: "oc:locality:py:190", ciudad: "San Juan Bautista", departamento: "Misiones" },
  { id: "oc:locality:py:191", ciudad: "San Miguel", departamento: "Misiones" },
  { id: "oc:locality:py:192", ciudad: "San Patricio", departamento: "Misiones" },
  { id: "oc:locality:py:193", ciudad: "Santa María de Fe", departamento: "Misiones" },
  { id: "oc:locality:py:194", ciudad: "Santa Rosa de Lima", departamento: "Misiones" },
  { id: "oc:locality:py:195", ciudad: "Santiago", departamento: "Misiones" },
  { id: "oc:locality:py:196", ciudad: "Villa Florida", departamento: "Misiones" },
  { id: "oc:locality:py:197", ciudad: "Yabebyry", departamento: "Misiones" },
  { id: "oc:locality:py:198", ciudad: "Alberdi", departamento: "Ñeembucú" },
  { id: "oc:locality:py:199", ciudad: "Cerrito", departamento: "Ñeembucú" },
  { id: "oc:locality:py:200", ciudad: "Desmochados", departamento: "Ñeembucú" },
  { id: "oc:locality:py:201", ciudad: "General José Eduvigis Díaz", departamento: "Ñeembucú" },
  { id: "oc:locality:py:202", ciudad: "Guazú Cuá", departamento: "Ñeembucú" },
  { id: "oc:locality:py:203", ciudad: "Humaitá", departamento: "Ñeembucú" },
  { id: "oc:locality:py:204", ciudad: "Isla Umbú", departamento: "Ñeembucú" },
  { id: "oc:locality:py:205", ciudad: "Laureles", departamento: "Ñeembucú" },
  { id: "oc:locality:py:206", ciudad: "Mayor José Martínez", departamento: "Ñeembucú" },
  { id: "oc:locality:py:207", ciudad: "Paso de Patria", departamento: "Ñeembucú" },
  { id: "oc:locality:py:208", ciudad: "Pilar", departamento: "Ñeembucú" },
  { id: "oc:locality:py:209", ciudad: "San Juan Bautista de Ñeembucú", departamento: "Ñeembucú" },
  { id: "oc:locality:py:210", ciudad: "Tacuaras", departamento: "Ñeembucú" },
  { id: "oc:locality:py:211", ciudad: "Villa Franca", departamento: "Ñeembucú" },
  { id: "oc:locality:py:212", ciudad: "Villa Oliva", departamento: "Ñeembucú" },
  { id: "oc:locality:py:213", ciudad: "Villalbín", departamento: "Ñeembucú" },
  { id: "oc:locality:py:214", ciudad: "Acahay", departamento: "Paraguarí" },
  { id: "oc:locality:py:215", ciudad: "Caapucú", departamento: "Paraguarí" },
  { id: "oc:locality:py:216", ciudad: "Carapeguá", departamento: "Paraguarí" },
  { id: "oc:locality:py:217", ciudad: "Escobar", departamento: "Paraguarí" },
  { id: "oc:locality:py:218", ciudad: "General Bernardino Caballero", departamento: "Paraguarí" },
  { id: "oc:locality:py:219", ciudad: "La Colmena", departamento: "Paraguarí" },
  { id: "oc:locality:py:220", ciudad: "María Antonia", departamento: "Paraguarí" },
  { id: "oc:locality:py:221", ciudad: "Mbuyapey", departamento: "Paraguarí" },
  { id: "oc:locality:py:222", ciudad: "Paraguarí", departamento: "Paraguarí" },
  { id: "oc:locality:py:223", ciudad: "Pirayú", departamento: "Paraguarí" },
  { id: "oc:locality:py:224", ciudad: "Quiindy", departamento: "Paraguarí" },
  { id: "oc:locality:py:225", ciudad: "Quyquyhó", departamento: "Paraguarí" },
  { id: "oc:locality:py:226", ciudad: "San Roque González de Santa Cruz", departamento: "Paraguarí" },
  { id: "oc:locality:py:227", ciudad: "Sapucai", departamento: "Paraguarí" },
  { id: "oc:locality:py:228", ciudad: "Tebicuarymí", departamento: "Paraguarí" },
  { id: "oc:locality:py:229", ciudad: "Yaguarón", departamento: "Paraguarí" },
  { id: "oc:locality:py:230", ciudad: "Ybycuí", departamento: "Paraguarí" },
  { id: "oc:locality:py:231", ciudad: "Ybytymí", departamento: "Paraguarí" },
  { id: "oc:locality:py:232", ciudad: "Benjamín Aceval", departamento: "Presidente Hayes" },
  { id: "oc:locality:py:233", ciudad: "Campo Aceval", departamento: "Presidente Hayes" },
  { id: "oc:locality:py:234", ciudad: "General José María Bruguez", departamento: "Presidente Hayes" },
  { id: "oc:locality:py:235", ciudad: "José Falcón", departamento: "Presidente Hayes" },
  { id: "oc:locality:py:236", ciudad: "Nanawa", departamento: "Presidente Hayes" },
  { id: "oc:locality:py:237", ciudad: "Nueva Asunción", departamento: "Presidente Hayes" },
  { id: "oc:locality:py:238", ciudad: "Puerto Pinasco", departamento: "Presidente Hayes" },
  { id: "oc:locality:py:239", ciudad: "Teniente Esteban Martínez", departamento: "Presidente Hayes" },
  { id: "oc:locality:py:240", ciudad: "Teniente Primero Manuel Irala Fernández", departamento: "Presidente Hayes" },
  { id: "oc:locality:py:241", ciudad: "Villa Hayes", departamento: "Presidente Hayes" },
  { id: "oc:locality:py:242", ciudad: "Antequera", departamento: "San Pedro" },
  { id: "oc:locality:py:243", ciudad: "Capiibary", departamento: "San Pedro" },
  { id: "oc:locality:py:244", ciudad: "Choré", departamento: "San Pedro" },
  { id: "oc:locality:py:245", ciudad: "General Elizardo Aquino", departamento: "San Pedro" },
  { id: "oc:locality:py:246", ciudad: "General Isidoro Resquín", departamento: "San Pedro" },
  { id: "oc:locality:py:247", ciudad: "Guayaibí", departamento: "San Pedro" },
  { id: "oc:locality:py:248", ciudad: "Itacurubí del Rosario", departamento: "San Pedro" },
  { id: "oc:locality:py:249", ciudad: "Liberación", departamento: "San Pedro" },
  { id: "oc:locality:py:250", ciudad: "Lima", departamento: "San Pedro" },
  { id: "oc:locality:py:251", ciudad: "Nueva Germania", departamento: "San Pedro" },
  { id: "oc:locality:py:252", ciudad: "San José del Rosario", departamento: "San Pedro" },
  { id: "oc:locality:py:253", ciudad: "San Estanislao", departamento: "San Pedro" },
  { id: "oc:locality:py:254", ciudad: "San Pablo", departamento: "San Pedro" },
  { id: "oc:locality:py:255", ciudad: "San Pedro de Ycuamandiyú", departamento: "San Pedro" },
  { id: "oc:locality:py:256", ciudad: "San Vicente Pancholo", departamento: "San Pedro" },
  { id: "oc:locality:py:257", ciudad: "Santa Rosa del Aguaray", departamento: "San Pedro" },
  { id: "oc:locality:py:258", ciudad: "Tacuatí", departamento: "San Pedro" },
  { id: "oc:locality:py:259", ciudad: "Unión", departamento: "San Pedro" },
  { id: "oc:locality:py:260", ciudad: "Veinticinco de Diciembre", departamento: "San Pedro" },
  { id: "oc:locality:py:261", ciudad: "Villa del Rosario", departamento: "San Pedro" },
  { id: "oc:locality:py:262", ciudad: "Yataity del Norte", departamento: "San Pedro" },
  { id: "oc:locality:py:263", ciudad: "Yrybucuá", departamento: "San Pedro" },
]

const LOCALITY_PROVENANCE = Object.freeze({
  identifierScheme: 'owncoding-internal',
  status: 'inherited-catalog',
  source: 'OwnCoding municipality catalog shared with MobOS',
  sourceUrl: 'https://github.com/dariodeoli/owncoding-ui/blob/2a72640eb67025d7947f91c839cb34a9d4241a43/src/catalog/ciudades.js',
})

export const LOCALITIES_PARAGUAY = Object.freeze(MUNICIPIOS.map(({ id, ciudad, departamento }) => Object.freeze({
  id, city: ciudad, department: departamento, provenance: LOCALITY_PROVENANCE,
})))

// Legacy rows deliberately retain exactly four keys.
export const CIUDADES_PARAGUAY = LOCALITIES_PARAGUAY.map(({ city: ciudad, department: departamento }) => ({
  ciudad,
  departamento,
  city: ciudad,
  department: departamento,
}))

export const DEPARTAMENTOS_PARAGUAY = [
  "Alto Paraguay",
  "Alto Paraná",
  "Amambay",
  "Asunción",
  "Boquerón",
  "Caaguazú",
  "Caazapá",
  "Canindeyú",
  "Central",
  "Concepción",
  "Cordillera",
  "Guairá",
  "Itapúa",
  "Misiones",
  "Ñeembucú",
  "Paraguarí",
  "Presidente Hayes",
  "San Pedro",
]

const norm = (valor) => String(valor || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim()

// Match exact normalized identity only; preserve custom input and ambiguity.
export function resolveLocality(city, department, catalog = LOCALITIES_PARAGUAY) {
  const input = { city, department }
  const unknown = { status: 'unknown', input, record: null }
  if (typeof city !== 'string' || !city.trim()) return unknown
  if (department !== undefined && typeof department !== 'string') return unknown
  const matches = catalog.filter(record =>
    (record.id === city || norm(record.city) === norm(city)) &&
    (department === undefined || norm(record.department) === norm(department)),
  )
  if (matches.length > 1) return { status: 'ambiguous', input, record: null }
  if (!matches.length) return unknown
  return { status: 'resolved', input, record: matches[0], matchedBy: matches[0].id === city ? 'id' : 'name' }
}

// Departamento de una ciudad por nombre exacto (sin acentos ni mayúsculas).
export function departamentoDe(ciudad) {
  const buscado = norm(ciudad)
  if (!buscado) return ""
  const fila = CIUDADES_PARAGUAY.find((item) => norm(item.ciudad) === buscado)
  return fila?.departamento || ""
}

// Busca por ciudad o departamento, con las coincidencias al principio primero.
// Devuelve las filas bilingües (`ciudad`/`departamento` y `city`/`department`).
export function buscarCiudad(texto, limite = 8) {
  const q = norm(texto)
  if (q.length < 2) return []
  return CIUDADES_PARAGUAY
    .filter(({ ciudad, departamento }) => norm(ciudad).includes(q) || norm(departamento).includes(q))
    .sort((a, b) => {
      const aInicio = norm(a.ciudad).startsWith(q) ? 0 : 1
      const bInicio = norm(b.ciudad).startsWith(q) ? 0 : 1
      return aInicio - bInicio || a.ciudad.localeCompare(b.ciudad, "es")
    })
    .slice(0, limite)
    .map(({ ciudad, departamento, city, department }) => ({ ciudad, departamento, city, department }))
}
