export {
  PhoneField,
  CountryPhoneSelect,
  CODIGOS_PAIS,
  parseTelefono,
  parseTelefonoInternacional,
  componerTelefono,
  telefonoE164,
  telefonoInternacionalValido,
  normalizarTelefono,
  internationalPhone,
  whatsappUrl,
  soloDigitos,
  codigoPais,
  telefonoVisible,
  telefonoValido,
  MENSAJE_TELEFONO,
  PAISES_TELEFONO,
  paisTelefonoPorIso,
  paisesDeCodigo,
  buscarPaisesTelefono,
} from './index.js'
