import React, { useState } from 'react'
import { Combobox, Popover, Tooltip, CloseButton, AppHeader, PublicHeader, ProfileCard, UserMenu, AccountSwitcher, NotificationCenter, AsyncButton, FooterPreset, CopyButton, ActionToolbar, Button, ThemeToggle, Modal, ToastProvider, useToast } from '../src/index.js'

const teams = [{ id: 'ventas', label: 'Ventas · equipo demo' }, { id: 'soporte', label: 'Soporte · equipo demo' }, { id: 'archivo', label: 'Archivo · no disponible', disabled: true }]
const nav = [{ label: 'Resumen', href: '#resumen', active: true }, { label: 'Actividad', href: '#actividad' }, { label: 'Documentación', href: '#documentacion' }]
const initialNotices = [{ id: '1', title: 'Pedido Demo listo', description: 'Evento ficticio, sin conexión a servicios.', read: false, type: 'operacion', group: 'Hoy' }, { id: '2', title: 'Sesión Demo revisada', read: true, type: 'cuenta', group: 'Ayer' }]

function AsyncScene() {
  const toast = useToast()
  const [fail, setFail] = useState(false)
  return <div className="space-y-4"><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={fail} onChange={event => setFail(event.target.checked)} />Simular error</label><AsyncButton action={() => toast.promise(() => new Promise((resolve, reject) => setTimeout(() => fail ? reject(new Error('Error simulado; podés reintentar.')) : resolve('demo'), 700)), { loading: 'Guardando fixture…', success: 'Fixture guardado localmente', error: 'No se guardó el fixture' })}>Guardar fixture</AsyncButton><Button variant="outline" onClick={() => toast.info('Elemento retirado solo de la muestra', { undo: { label: 'Deshacer', onClick: () => toast.success('Elemento restaurado en la muestra') } })}>Probar aviso con Deshacer</Button></div>
}

export function ReusablePreview({ name }) {
  const [value, setValue] = useState(null)
  const [multiple, setMultiple] = useState(false)
  const [multiValue, setMultiValue] = useState([])
  const [state, setState] = useState('ready')
  const [open, setOpen] = useState(false)
  const [dirty, setDirty] = useState(false)
  const [busy, setBusy] = useState(false)
  const [notices, setNotices] = useState(initialNotices)
  const [variant, setVariant] = useState('public')
  const [status, setStatus] = useState('Fixture local; sin autenticación, envío ni persistencia.')
  const actions = <><ThemeToggle /><UserMenu name="Persona Demo" items={[{ label: 'Perfil de muestra', onClick: () => setStatus('Perfil local seleccionado.') }, { label: 'Preferencias de muestra', onClick: () => setStatus('Preferencias locales seleccionadas.') }]} /></>
  let scene
  if (name === 'Combobox') scene = <div className="space-y-4"><div className="flex flex-wrap gap-3"><label><input type="checkbox" checked={multiple} onChange={event => setMultiple(event.target.checked)} /> Selección múltiple</label><label>Estado <select value={state} onChange={event => setState(event.target.value)} className="rounded border border-interactivo bg-ink p-2"><option value="ready">Listo</option><option value="loading">Cargando</option><option value="error">Error</option><option value="empty">Vacío</option></select></label></div><Combobox label="Equipos de muestra" multiple={multiple} value={multiple ? multiValue : value} onChange={multiple ? setMultiValue : setValue} items={state === 'empty' ? [] : teams} loading={state === 'loading'} error={state === 'error' ? 'No se pudieron cargar las opciones de muestra.' : undefined} renderItem={item => <span>{item.label}</span>} /><p className="text-sm text-mute">Selección: {JSON.stringify(multiple ? multiValue : value)}</p></div>
  if (name === 'Popover') scene = <Popover label="Acciones contextuales de muestra" trigger="Abrir acciones"><div className="max-w-xs space-y-2"><h4 className="font-bold">Pedido Demo</h4><p className="text-sm text-mute">Escape cierra y restaura el foco; el panel se ajusta al espacio disponible.</p><Button onClick={() => setStatus('Acción contextual local ejecutada.')}>Revisar fixture</Button></div></Popover>
  if (name === 'Tooltip') scene = <div className="flex flex-wrap items-center gap-3"><Tooltip trigger="¿Cómo funciona?" label="Ayuda de la muestra">Ayuda breve accesible con foco, puntero o toque. Para acciones, usá Popover.</Tooltip><span className="text-sm text-mute">Probá Tab, Escape o tocar el botón.</span></div>
  if (name === 'AppHeader') scene = <AppHeader title="Operaciones Demo" items={nav} actions={actions}><div className="mt-3 text-xs text-mute">Modelo administrativo; menú adaptable a móvil.</div></AppHeader>
  if (name === 'PublicHeader') scene = <PublicHeader title="Producto Demo" items={nav} actions={<Button onClick={() => setStatus('Solicitud simulada; no se envió información.')}>Conocer la muestra</Button>} />
  if (name === 'ProfileCard') scene = <ProfileCard name="Persona Demo" email="demo@example.invalid" role="Administración · muestra local" actions={<ActionToolbar><Button variant="outline" onClick={() => setStatus('Edición de perfil simulada.')}>Editar perfil</Button><ThemeToggle /></ActionToolbar>} />
  if (name === 'UserMenu') scene = <UserMenu name="Persona Demo" items={[{ label: 'Ver perfil', onClick: () => setStatus('Perfil local seleccionado.') }, { label: 'Preferencias', onClick: () => setStatus('Preferencias locales seleccionadas.') }, { label: 'Cerrar sesión de muestra', peligro: true, onClick: () => setStatus('No existe una sesión real para cerrar.') }]} />
  if (name === 'AccountSwitcher') scene = <div className="space-y-3"><AccountSwitcher accounts={teams} value={value} onChange={setValue} /><p className="text-sm text-mute">Cuenta local: {value ?? 'sin selección'}. Cambiar aquí no modifica permisos.</p></div>
  if (name === 'NotificationCenter') scene = <NotificationCenter items={notices} types={[{ id: 'operacion', label: 'Operaciones' }, { id: 'cuenta', label: 'Cuenta' }]} onSelect={item => { setNotices(current => current.map(notice => notice.id === item.id ? { ...notice, read: true } : notice)); setStatus(`Revisado localmente: ${item.title}`) }} onMarkAllRead={() => setNotices(current => current.map(item => ({ ...item, read: true })))} hasMore onLoadMore={() => setStatus('No hay más fixtures locales.')} />
  if (name === 'CloseButton') scene = <div className="space-y-3"><div className="flex flex-wrap gap-3"><label><input type="checkbox" checked={dirty} onChange={event => setDirty(event.target.checked)} /> Cambios sin guardar</label><label><input type="checkbox" checked={busy} onChange={event => setBusy(event.target.checked)} /> Operación ocupada</label></div><Button onClick={() => setOpen(true)}>Abrir diálogo de muestra</Button><CloseButton onClick={() => setStatus('Cierre independiente ejecutado.')} /><Modal open={open} onClose={() => setOpen(false)} title="Cierre protegido" dirty={dirty} busy={busy}><p>El botón respeta el mismo cierre protegido del diálogo.</p><CloseButton /></Modal></div>
  if (name === 'AsyncButton') scene = <ToastProvider><AsyncScene /></ToastProvider>
  if (name === 'CopyButton') scene = <div className="space-y-3"><p className="rounded-lg border border-interactivo p-3 font-mono text-sm">PEDIDO-DEMO-001</p><CopyButton text="PEDIDO-DEMO-001" onCopied={() => setStatus('Código de muestra copiado.')} /><p className="text-xs text-mute">Usa el portapapeles solo al pulsar; muestra errores si el navegador lo bloquea.</p></div>
  if (name === 'ActionToolbar') scene = <ActionToolbar label="Acciones del pedido demo"><Button onClick={() => setStatus('Edición local seleccionada.')}>Editar</Button><Button variant="outline" onClick={() => setStatus('Exportación simulada; no se descargó ningún dato.')}>Exportar</Button><UserMenu name="Más" items={[{ label: 'Archivar fixture', onClick: () => setStatus('Archivo simulado.') }]} /></ActionToolbar>
  if (name === 'FooterPreset') scene = <div className="space-y-3"><label>Modelo <select value={variant} onChange={event => setVariant(event.target.value)} className="rounded border border-interactivo bg-ink p-2"><option value="public">Web pública</option><option value="app">Aplicación</option><option value="auth">Acceso</option></select></label><FooterPreset variant={variant} name="Producto Demo" version="v1.0.0" links={[{ etiqueta: 'Privacidad', href: '#privacidad' }, { etiqueta: 'Términos', href: '#terminos' }]} columns={[{ titulo: 'Producto', enlaces: [{ etiqueta: 'Funciones', href: '#funciones' }, { etiqueta: 'Ayuda', href: '#ayuda' }] }]} callToAction={{ titulo: 'Conocé el producto', descripcion: 'Modelo reutilizable; enlace de muestra.', enlace: { etiqueta: 'Ver funciones', href: '#funciones' } }} /></div>
  return <div data-demo-family="reusable" data-demo-export={name} className="min-w-0 space-y-4">{scene}<p role="status" className="text-xs text-mute">{status}</p></div>
}
